---
- name: Install dependencies
  ansible.builttin.package:
        name: 
          - wget 
          - tar 
          - git
        state: present

- name: Download shadowsocks-rust archive
  get_url:
        url: "{{ shadowsocks_rust}}"
        dest: "/tmp/shadowsocks.tar.xz"
        mode: 0644
           
- name: Extract shadowsocks-rust archive
  unarchive:
        src: "/tmp/shadowsocks.tar.xz"
        dest: "/bin"
        remote_src: yes
        creates: /bin/ssserver

- name: Download V2Ray plugin
  get_url:
        url: "{{ V2Ray_plugin }}"
        dest: "/tmp/v2ray.tar.gz"
        mode: 0644
            
- name: Extract V2Ray archive
  unarchive:
         src: "/tmp/v2ray.tar.gz"
         dest: "/bin"
         remote_src: yes
         extra_opts: [--transform=s|.*|v2ray-plugin|]
         creates: /bin/v2ray-plugin

   
- name: Create Shadowsocks-Rust config directory
  file:
       path: /etc/shadowsocks
       state: directory

- name: Generate ssserver.service
  template: 
    src: ssserver.j2 
    dest: etc/systemd/system/ssserver.service 
    mode: 0555
  notify:
     - Reload systemd
     

- name: Generate config.json RedHat
  template: 
   src: config.j2 
   dest: /etc/shadowsocks/config.json 
   mode: 0555
  notify:
    - Start ssserver
    - Open port RedHat
  when: ansible_os_family == "RedHat"

- name: Generate config.json Debian
  template: 
   src: config.j2 
   dest: /etc/shadowsocks/config.json 
   mode: 0555
  notify:
    - Enable UFW
    - Open port Debian
    - Reload UFW
    - Start ssserver   
  when: ansible_os_family == "Debian"

  
