# handlers file for deploy_shadowsoks_rust
---
- name: Reload systemd
  systemd:
    daemon_reload: yes
    
- name: Start ssserver
  systemd:
    name: ssserver
    state: started
    enabled: yes

- name: Reload ssserver
  systemd:
    name: ssserver
    state: reloaded
    enabled: yes

- name: Reload UFW
  shell: ufw reload



