# handlers file for deploy_shadowsoks_rust
---
- name: Reload systemd
  systemd:
    daemon_reload: yes
    
- name: Start ssserver
  systemd:
     name: ssserver
     state: started
     enabled: yes

- name: Reloaded ssserver
  systemd:
     name: ssserver
     state: reloaded
     enabled: yes

- name: Open port RedHat
  firewalld:
    port: "{{ port_enable }}"
    proto: "{{ proto_enable }}"
    permanent: yes
    state: enabled
    immediate: yes

- name: Enable UFW
  shell: ufw --force enable

- name: Reload UFW
  shell: ufw reload

- name: Open port Debian
  ufw:
    rule: allow
    port: "{{ port_enable }}"

